SOMAS2021/SOMAS2021

- cmd/backend/main.go
Makes logging more robust: Windows paths do not use forward slashes.
> Logger filepath fix

- pkg/infra/tower.go
Tower used base agent functions to access state. These functions could be overridden by custom agents accidentally.
> Replace functions by state access in tower

- cmd/backend/main.go
- pkg/infra/tower.go
- pkg/simulation/simulation.go
- pkg/utils/globalTypes/day/day.go
Ticks per day now dependent on other variables.
This PR is aiming to solve the issue #13 . Day and tower parameters as set from discussion in meeting. 
From meeting: input params: composition of agents (and therefore total number of agents), number of agents per floor (this will need to be a factor of the total number of agents), time spent per floor. (Courtesy of @jzzheng22 )
Tested by observing logs of reshuffling etc while changing `ticksPerFloor` in main.go - changes day length as expected.
> Day & Tower Input Parameters.

- cmd/backend/main.go
- config.json
- pkg/config/configparameters.go
- pkg/infra/baseagent.go
- pkg/infra/tower.go
- pkg/simulation/simulation.go
- pkg/utils/globalTypes/health/health.go
- pkg/utils/usefulFunctions/usefulfunctions.go
- pkg/utils/utilfunctions/utilfunctions.go
This solves issue #82
Main now loads the runtime parameters from a json file, and puts them inside a `ConfigParameters` struct that contains pretty much all parameters needed. 
New `config` package created for the `ConfigParameters` struct and the `LoadParamFromJson` function
The `LoadParamFromJson` function  is used to parse the json and convert it into a struct and is also hopefully very similar to what will be required for the frontend communication to parse the json ( issue #81 )
Also added functionality for command-line flags to allow the used to choose the location of the config file, however if none is provided, then it will use the config.json file which already contains the default values of previous commit.
> Parametrise backend using a config json file

- pkg/infra/tower.go
Closes #116.
Note that this function now allows agents to be shuffled onto their previous floors.
> Rewrite Reshuffle() to remove infinite loop

- pkg/infra/tower.go
- pkg/simulation/simAgent.go
- pkg/simulation/simulation.go
-Added deadAgents mapping parameter to tower struct
-Added UpdateDeadAgents function
-Added DeadAgents function
-Added logs for when agent dies
-Added log for summary of dead agents at end of simulation
Added parameter to tower to track dead agents during the simulations.
Added logs for when agent has died and a summary at the end of the simulation.
Added functions to tower.
Not sure if this is the best way to store and track this information. Please tell me if you have any other suggestions.
Currently works with agentType as int but I understand this is likely to change, so the changes here will have to be modified slightly when this happens.
Increased the number of simulation days for testing and checked logs over multiple simulations.
> Logging dead agents during simulation

- pkg/infra/baseagent.go
- pkg/infra/tower.go
Following discussion of how we will be handling treaties, I'm changing the code that is run at the end of each day:
- At the end of a day, the function `t.endOfDay()` is called.
- This function then calls:
- `agent.hpDecay()`
- `agent.increaseAge()`
- `agent.updateTreaties()` - this is currently commented out, however once we implement the other treaty code, can be uncommented.
-  There is also an initial implementation, commented out, for `updateTreaties()`.
I've also moved `hpDecay()` from tower to agent, and mildly refactored it to use `utilFunctions.MinInt()` so we don't have to cast the numbers to floats.
I've also added an age field to the base agent - this will be needed when we have treaties.
> Add code to handle agent updates at end of day

- config.json
- main.go
- pkg/agents/team7/agent1/agent.go
- pkg/config/configparameters.go
- pkg/simulation/simAgent.go
Closes Issue #128 and #141 
When the backend runs in serve mode, whenever it gets a HTTP request, it loads the parameters from the request body, and runs the simulation. It also generates a response and sends it back. The response contains the log file name, and a success boolean. Currently the success is hard coded, but soon I will make it depend on a timeout in a different PR (issue #142)
It also now allows setting a log file name through the config using parameter `LogFileName` either through the config.json, or through the HTTP request. This will be useful for the dashboard to make it easier to differentiate between different logs.
Screenshots of requests and responses:
<details>
<summary>HTTP Request, no log name change</summary>
</details>
<details>
<summary>HTTP Request, with name …
> Implemented HTTP Request and Response for Frontend communication, and option to define log file name using config

- pkg/infra/tower.go
Don't need this mutex - we never call that function at all, but also we never modify the list of agents inside a goroutine.
> Remove unnecessary mutex

- pkg/messages/baseMessage.go
- pkg/messages/responseMessage.go
Bugfix: forgot to put `senderID` in reply interface.
Also changing `RequestId` to `RequestID` for consistency
> Fix reply function: missing senderID in interface

- pkg/simulation/simIteration.go
Bug where if an agent dies in the last tick their death isn't reported at the end in the death summary.
Example:
```
{"agent_id":"7bf7d0e2-8c96-4d1b-854e-4d7d0363ca5c","agent_type":5,"level":"info","msg":"Killing agent","reporter":"agent","time":"2021-12-30T15:17:07Z"}
{"agent_id":"7bf7d0e2-8c96-4d1b-854e-4d7d0363ca5c","agent_type":5,"level":"info","msg":"Setting hp to 0","reporter":"agent","time":"2021-12-30T15:17:07Z"}
{"agent_id":"abe8652e-3a7a-409d-9aa5-89e04893f050","agent_type":1,"level":"info","msg":"Setting hp to 44","reporter":"agent","time":"2021-12-30T15:17:07Z"}
{"agent_id":"0c156615-ad79-4cbf-9366-c6ae7830e5e8","agent_type":1,"level":"info","msg":"Setting hp to 29","reporter":"agent","time":"2021-12-30T15:17:07Z"}
{"agent_id":"6624452b-902f-42fa-9337-5e52f6f994ad","agent_type" …
```
> Move agent replacement to end of day instead of start of day

- config.json
- main.go
- pkg/config/configparameters.go
- pkg/infra/tower.go
- pkg/simulation/simAgent.go
- pkg/simulation/simIteration.go
- pkg/simulation/simulation.go
- pkg/utils/globalTypes/day/day.go
- pkg/utils/logging/logging.go
- pkg/utils/logging/statelog.go
Closes #175 
Added `UseFoodPerAgentRatio` and `FoodPerAgentRatio` config parameters to allow to automatically set the amount of food depending on the number of agents. 
If `UseFoodPerAgentRatio` is true, then it multiplies `FoodPerAgentRatio` by number of agents to calculate total food. It ignores the `FoodOnPlatform` parameter if it is set
If  `UseFoodPerAgentRatio` is false, then it uses `FoodOnPlatform` and ignores `FoodPerAgentRatio`
I updated the config.json to include default parameters for them, and added error handling in case any of these three parameters are not set correctly.
> Implemented Food Per Agent Ratio

- config.json
- main.go
- pkg/config/configparameters.go
Closes #142
Added a parameter `SimTimeoutSeconds` to limit the amount of time used for simulation, and return an error if it is exceeded. 
If it is running in serve mode, if timeout is exceeded then it will return a HTTP 500 Internal Server Error with a timeout message, as seen below
<details>
<summary> Timeout error in serve mode </summary>
</details>
If it is running in a single simulation mode, if timeout is exceeded it both prints that there was a timeout error and appends it to the log (unsure if I should handle it differently, let me know if there is a better way)
> Added Timeout functionality

- pkg/agents/randomAgent/agent.go
- pkg/agents/team1/agent1/agent.go
- pkg/agents/team1/agent2/agent.go
- pkg/agents/team2/config.go
- pkg/agents/team3/agentMain.go
- pkg/agents/team4/agent1/agent.go
- pkg/agents/team5/agent1/agent.go
- pkg/agents/team6/config.go
- pkg/agents/team7/agent1/agent.go
- pkg/infra/baseagent.go
- pkg/infra/baseagent_errors.go
Add PlatOnFloor function to tell agents 
Fix design to only return foodTaken, not tower states (so no more -1 returned)
Edit from Jason: `TakeFood()` now returns two values, a `food.FoodType` and an `error`. `food.FoodType` is how much food an agent actually managed to take, and if `err != nil` then something went wrong - either you have already eaten, the platform is not on your floor, or you entered a negative amount of food to take.
> Add PlatOnFloor function for agents

- main.go
- pkg/config/configparameters.go
Closes #171 
When the application runs in serve mode, it will now also listen to the /directory endpoint, and when it receives a request, it will return a list of all the existing folders inside the log folder:
<details>
<summary> /directory request </summary>
</details>
If the folder does not exist, it returns a HTTP 500 Internal Server Error with an error message:
<details>
<summary> /directory request with no log folder existing </summary>
</details>
Also an additional change was to return the error resulted by being unable to put the result struct into json format for the response in the /simulate endpoint from 400 Bad Request to 500 Internal Server Error.
> Infra directory endpoint

- pkg/infra/baseagent.go
Added a field to the logs which displays the number of days lived by an agent when it is killed
Closing #196
> logging days lived by an agent

- main.go
- pkg/config/configparameters.go
- pkg/simulation/simulation.go
Closes #189. 
Removed some unnecessary prints related to directories. They were left from a template i used. Oops.
Also cleaned up the console prints by using log.Info and log.Error instead of fmt.Println 
Edit: Also renamed logFileName to LogFolderName everywhere except in the json parsing, so it is still compatible with the current frontend, and also now the directory array is initialised to empty instead of nil (as per Jaafar's request)
> Cleaned up console prints

- main.go
- pkg/simulation/simIteration.go
- pkg/simulation/simulation.go
So up until now, when a timeout happened, main would show that there was a timeout, but the goroutine would actually keep running in the background until it was complete, wasting resources.
It turns out there is no built in way to kill a thread / goroutine in golang. So i had to do it manually, by checking if timeout was triggered every tick. Might not be the neatest implementation, but it works and doesn't seem too bad. If you have any recommendations let me know.
Tested using manual prints to ensure that once a timeout was triggered, the simulate and simulationLoop functions would not continue.
> Timeouts now end the goroutines rather than keeping them running until the end

- pkg/agents/team5/messages.go
Overrides the base agent's HandlePropogate message function to manually run our Handle... functions on any State... messages, resulting in our agents "remembering" information which we pass on.
> Override HandlePropogate message function to process State... messages

- config.json
- pkg/config/configparameters.go
We had things like `Team1AgtOne` and `Team7Agents` which was a headache to keep track of in the frontend. Renamed everything to `TeamXAgents` in the config. Agent 2 of Team 1 is named `Team1Agents2` and can still be passed by the config (but not the frontend since it really doesn't do anything).
Prior to the fix, when you create a simulation via frontend, you would team1 and team7 agents set to 0 (name mismatch). Now everything is set correctly and `Team1Agents2` is set to 0 if frontend is creating the simulation
> Consistent config names

- main.go
- pkg/utils/logging/simstatus.go
This is related to backend part of issue #212
This feature will allow frontend to easily tell the status of any simulation, and see if it still running, if it finished successfully, or if it timed out
During each run, inside the log folder there is now a status.json file created. When simulation starts, it contains the following: 
`{"status":"running"}`
If the simulation finished successfully, it gets updated to the following: 
`{"status":"finished successfully"}`
If the simulation times out it gets updated to the following: 
`{"status":"timed out"}`
The actual strings used can be modified if anyone has any suggestions.
> Simulation now creates and updates a status.json file

- .github/workflows/main.yaml
Replace npm install with ci to ensure same dependency tree every build
> Replace NPM install with ci

- pkg/infra/baseAgent.go
- pkg/utils/globalTypes/health/health.go
- pkg/utils/globalTypes/health/health_test.go
Perform math.Round() before to cast floats to integers in the health functions (updateHP, HPDecay, FoodRequired). This operation allows for better performance of the FoodRequired function
The precision gained by this method was analysed by using the best set of health parameters we have so far, in a matlab script:
tau=15;
w=48;
b=5;
s=0.2;
WeakLevel=10;
HPCritical=3;
HPReqCToW=5;
> Round() before int casting

- pkg/agents/team6/config.go
Added variables for trust and means of keeping track of neighbours. Will continue with implementing trust in parallel with messages in future
Changed initialisation of array in config:
`memory{}` looks like an empty struct of type memory. `make(memory, 0)` clarifies that it's a slice (and calls `runtime.makeslice`)
neighbours struct stores the conceived IDs of the above and below neighbours for use in the trust map
> [TEAM6] Trust

- frontend/src/Components/Results/Graphs/MultiBarChart.tsx
- frontend/src/Components/Results/Graphs/PieChart.tsx
- frontend/src/Components/Results/Stats.tsx
- frontend/src/Helpers/Logging/Message.ts
- frontend/src/Helpers/Result.ts
- frontend/src/Helpers/Utils.ts
- pkg/infra/baseAgentMessages.go
- pkg/messages/proposeTreatyMessage.go
- pkg/simulation/simulation.go
- pkg/utils/logging/statelog.go
See title. Chart with all message types is a bit doomed, not really sure what better other way to display it. For convenience I've added a MultiBarChart and PieChart to our graph arsenal, but when testing our the visualizations much preferred the stacked bars option so I left it at that (though feel free to amend)
Treaties accept/reject
Message types per agent
> Add messages logging for message type counts and treaty accept/reject stats

- pkg/utils/logging/statelog.go
#312 did this
We didn't test with random agents, the log access in the array was wrong (enum indexing starts at 1 not 0)
> [HOTFIX] Death log array access
