cmd/backend/main.go
pkg/infra/baseagent.go
pkg/infra/tower.go

Implements only allowing agents to take food once per day. Parameter is reset in hpDecay function.
Adding hasEaten parameter to Base Agent structure. Prevents agents from taking food multiple times per day.
Added functions to obtain or update value of hasEaten 
Alter if statement in TakeFood to include check for !hasEaten
Closes #26 
Added new logs for when food is taken from the platform

Adding hasEaten to base agent struct

---

pkg/infra/baseagent.go
pkg/infra/tower.go

If agent and platform are on the same floor **return the amount of food on the platform**, otherwise return 0 (since agents should not know how much food is on the platform if it's not on their floor). 
This PR is aiming to solve the issue #32  (Add getter function CurrPlatFood() to tower). 
- Have tested it with the existing agents and it works :)

Added getter function CurrPlatFood

---

.github/workflows/main.yaml

Run the main code in CI/CD to make sure it executes
https://github.com/SOMAS2021/SOMAS2021/actions/runs/1569363568

Add run to CI/CD

---

cmd/backend/main.go
pkg/agents/randomAgent/agent.go
pkg/simulation/simulation.go

Adding an agent that takes a random amount of food between 0 and 100. Currently does nothing else.
Solves #33. Creates a random agent for experimentation
Random agent that only takes a food amount between 0 and 100. Does not sent messages
Ran simulation and checked log files to see amount of food taken was random.

Adding Random Agent

---

cmd/backend/main.go
pkg/agents/team3/agentMain.go
pkg/agents/team3/emotions.go
pkg/agents/team3/foodCalculations.go
pkg/agents/team3/messages.go
pkg/simulation/simAgent.go

Added files for team 3's agent. 
Modified some of the infra files to add the new agent and added logs for this agent in its Run function. 
Ran files multiple times and checked logs to ensure correct operation

Add Team 3 MVP

---

pkg/infra/baseagent.go

expose health info

---

cmd/backend/main.go
pkg/agents/team3/agentMain.go
pkg/agents/team3/emotions.go
pkg/agents/team6/config.go

Fixes #60 - all seeding now happens in main
Team3 + Team6 seeding removed
JSON still generates randomly, all tests are ok

move rand seed

---

pkg/agents/team5/agent1/agent.go

added a map for agent memory to the agent type, and created a Memory struct for the values of the map

Team5 mvp memory

---

pkg/infra/baseagent.go

Issue #80 
Allowed to take 0 food and then an additional amount (>0) in the same day.
Tested on agent 1 in team 1 to see before and after taking 0 food and then 10 food

change TakeFood to work for 0 food taken as well

---

pkg/infra/baseagent.go

Initialise daysAtCritical to 0

---

pkg/infra/baseagent.go

Added at the request of Matt Scott

Add DaysAtCritical getter function

---

pkg/agents/team6/config.go
pkg/agents/team6/strategies.go
pkg/infra/baseagent.go

Updated food intake strategies based on new HP functions in main
Agents take food according to social motive and HP function
No conflicts with infra files - logs have been run to confirm that behaviours are correct

Team6 Food Intake Strategy Update

---

pkg/infra/tower.go
pkg/simulation/simIteration.go

Reshuffling before simulation starts.
Issue fixes #52 
Printed logs

Initial reshuffle

---

pkg/infra/baseagent.go

Nothing but a hard days work.
Fixes #99

Checking for negative food

---

cmd/backend/main.go
pkg/agents/team6/strategies.go
pkg/infra/tower.go
pkg/utils/globalTypes/health/health.go

Parametrises magic numbers in HP function

Resolves #108 and #113

---

Makefile

Change make clean to remove logs directory

---

.github/workflows/package.yaml

Sync docker with deployment + remove goreleaser since the versioning with tags (it's not really safe tags can be triggered from any branch)

[INFRA/CICD] Update packaging

---

pkg/agents/team5/agent1/agent.go

added function to get max  hp and percentage hp
also changed existing hp getters to call the percentageHP function

Team5 maxhp

---

pkg/infra/baseagent.go

Refactor updateHP

---

pkg/agents/team6/strategies.go
pkg/utils/globalTypes/health/health.go

Add foodRequired function to health package

---

.github/workflows/main.yaml
frontend/src/App.tsx

Frontend NPM install and NPM build prod check
Failure on warnings or errors: https://github.com/SOMAS2021/SOMAS2021/runs/4676180077?check_suite_focus=true

[CICD] Frontend Pipeline

---

.github/workflows/main.yaml
frontend/package-lock.json
frontend/package.json

Just realized I could add this to pipeline.
Frontend linter (using "prettier" package) to ensure code style consistency

Frontend linter

---

frontend/src/App.tsx
frontend/src/Components/Results.tsx
frontend/src/Components/Sidebar.tsx
frontend/src/Components/Toaster.tsx
frontend/src/Helpers/Log.tsx

Load logs using /logs
Includes error handling

[APP] Load directory into frontend

---

pkg/infra/baseagent.go
pkg/simulation/simAgent.go

Fix death logs

---

pkg/infra/baseAgentMessages.go

Accidentally left this in #205... woops. Maybe we shouldn't do PRs at 2am...

Remove HandleAskHP implementation from base agent

---

pkg/agents/team1/agent1/agent.go
pkg/messages/treaty.go

Sorry! Added value fields in treaties.

Add value fields to treaties

---

frontend/src/Helpers/API.ts

Will be better at reviewing code

[APP] Remove hardcoded endpoint

---

main.go
pkg/config/configparameters.go

This is related to backend part of Issue #213 
Now every time you run a simulation, the config.json file for that simulation will be saved in the logs folder together with the other logs. This will allow the frontend to pull and display the configs for each run afterwards

The config.json for each run is now saved inside the logs folder

---

frontend/src/Components/NewRunConfig/AdvancedSettings/AdvancedSettings.tsx
frontend/src/Components/NewRunConfig/ParameterLabels.ts
frontend/src/Components/NewRunConfig/Settings/Settings.tsx
frontend/src/Helpers/SimConfig.tsx

Can now select which choice of food input method.
Added mins on the numbers for inputs.
Code Clean Up To Do, This is only a temp UI change to get the choice of food input out for people.

[APP] Frontend UI improvements

---

.gitignore
frontend/package-lock.json
frontend/package.json
frontend/src/Helpers/API.ts

No more changing API.ts back and forth

[APP] Use .env file

---

frontend/src/Helpers/Utils.ts

[HOTFIX] Divide by 0

---

pkg/agents/team6/behaviours.go
pkg/agents/team6/communication.go
pkg/agents/team6/config.go
pkg/agents/team6/consumption.go

Moving average filter allows for keeping track of average food intake + discounting of previous intakes
paramWeights are updated using an example algorithm which we can fix after discussion
Rewritten weight array as struct and fixed accordingly in other files
Tested in main loop - weight updates work technically but are quite useless atm. Need discussion with group

[TEAM6] EMA filter for food intake + paramWeight update

---

frontend/src/Components/Results/Stats.tsx
frontend/src/Helpers/Utils.ts

Self explanatory, but additionally moved back to utils because it made more sense to me to be with Average etc. Fixes -inf and inf coming up on the dashboard

Add empty array checks to min and max

---

run_docker.sh

cba to keep typing out the same commands lmao

Add script to build and run Docker image

---

frontend/src/Helpers/Logging/Utility.ts

That's on me, I didn't review extensively, filename loading issues on the server (but maybe was working locally)

Hotfix frontend Utility pull

---

frontend/.env
pkg/agents/team3/agentMain.go
pkg/agents/team3/emotions.go
pkg/agents/team3/foodCalculations.go
pkg/agents/team3/messages.go
pkg/agents/team3/treaties.go

Update message sending
Update and finetune the effect of messages in our agent
Handling and accepting treaties implemented
Sending and propagating treaties implemented
New variables to store knowledge the agent uses in other functions

Team3 treaties and messages

---

config.json
frontend/src/Components/NewRunConfig/ParameterGroups/FileName.tsx
frontend/src/Components/Results/Results.tsx
frontend/src/Components/Story/StoryViewer.tsx
frontend/src/Helpers/API.ts
frontend/src/Helpers/Logging/Food.ts
frontend/src/Helpers/Logging/StoryLog.ts
frontend/src/Helpers/Result.ts
frontend/src/Helpers/SimConfig.ts
main.go
pkg/config/configparameters.go
pkg/config/readlog.go
pkg/simulation/simulation.go
pkg/utils/execution/common.go
pkg/utils/execution/localrun.go
pkg/utils/execution/maxtick.go
pkg/utils/execution/server/directory.go
pkg/utils/execution/server/readfile.go
pkg/utils/execution/server/simulate.go
pkg/utils/logging/simstatus.go
pkg/utils/logging/statelog.go

- Added optional tick filter at the backend /read endpoint
- Change on frontend how we read a story
- Make logging the story optional
- Reduce food log size

[APP] Fix memory, make story optional

---

pkg/agents/team5/utils.go

[Team 5] Remove unused function

---

pkg/agents/team3/messages.go
pkg/agents/team3/treaties.go

Just a quick debug of the direction in which we send a message.

[Team 3] Fix message directions

---

pkg/infra/baseAgent.go

Remove hardcoded 100
Use correct HP in logs

Hotfix HP log

---

pkg/agents/team6/treaties.go

Proposing a cleaner treaty function code

[TEAM6] Rewrite treaties

---

frontend/src/Components/Results/Stats.tsx
frontend/src/Helpers/Utils.ts

Self explanatory. I could probably reuse some of the other code. to get averages instead of adding a whole new function - lmk if you think this should be done

Add average age on death per agent graph

---

pkg/agents/team4/finalAgent/utils.go

[Hotfix] Memory Accesses

---

pkg/agents/team6/consumption.go

Correct a small mistake in our code I just discovered. 
As this PR is after the deadline, I leave you the choice of accepting it or not. The correction is rather small and will not affect a lot our agent's strategy. However, the previous version of the code was leading to an agent which was not honest in some cases (if a NewRequestTakeFood message (and not treaty as not implemented) was sent).

[Team 6] Fix typo

---

pkg/simulation/simIteration.go
pkg/simulation/simulation.go

Move timeout call to correct place

[HOTFIX] Timeout

---

frontend/src/Components/CollapsingSection.tsx
frontend/src/Components/Results/Graphs/MultiScatterChart.tsx
frontend/src/Components/Results/Results.tsx
frontend/src/Components/Results/Stats.tsx
frontend/src/Components/Results/Stats/DeathStats.tsx

Per agent stabilization

---

pkg/agents/team7/agent1/agent.go

[Team 7] Update greediness calculation parameter

---

frontend/src/Components/Results/Stats/OtherStats.tsx
frontend/src/Helpers/Utils.ts
pkg/agents/team1/agent1/agent.go
pkg/config/configparameters.go
pkg/simulation/simulation.go
pkg/utils/globalTypes/agent/agent.go
pkg/utils/globalTypes/agent/agenttype_string.go
pkg/utils/logging/statelog.go
pkg/utils/utilFunctions/utilFunctions_test.go

Self explanatory. Additionally made util functions return tuples of labels and data.

Update messages and treaties graphs to only show data for present agents

---

pkg/messages/baseMessage.go
pkg/messages/messagetype_string.go
pkg/utils/logging/statelog.go

Remove unused message types

---

frontend/package-lock.json
frontend/package.json
frontend/src/Components/Results/Graphs/MultiScatterChart.tsx
frontend/src/Components/Results/Graphs/ScatterChart.tsx
frontend/src/Components/Results/Stats/DeathStats.tsx
frontend/src/Components/Results/Stats/OtherStats.tsx
frontend/src/Helpers/Logging/Death.ts
frontend/src/Helpers/Utils.ts
frontend/src/index.css
pkg/utils/logging/statelog.go

- Fix agent type deaths
- Add zoom
- Add units to axis

Fix death graph, add zoom, add axes units

---

frontend/src/Components/Results/Graphs/ScatterChart.tsx
frontend/src/Components/Results/Stats/OtherStats.tsx
frontend/src/Helpers/Logging/Food.ts
frontend/src/Helpers/Result.ts
pkg/infra/tower.go
pkg/simulation/simulation.go
pkg/utils/logging/statelog.go

Logging food per floor average

---

pkg/agents/randomAgent/agent.go
pkg/agents/team1/README.md
pkg/agents/team1/agent2/agent.go
pkg/config/configparameters.go
pkg/infra/baseAgent.go
pkg/simulation/simIteration.go

https://www.youtube.com/watch?v=HIcSWuKMwOw

Minor cleanups
